apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    project: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    name: {{ .Chart.Name }}
    githash: {{ .Values.deploy.imageTag | quote }}
# Create key - value entries in the data map that other files can look up
# Load them into the environment by using configMapRef in the deploy.yaml file
data:
  PROJECT_NAME: {{ .Chart.Name | quote }}
  NAMESPACE: {{ .Release.Namespace | quote }}

  REDIS_CREATE: {{ .Values.redis.create | quote }}
  # Specifying this here instead of in values.yaml allows us to avoid hardcoding the
  # hostname (aladdin-demo-redis) in a way that would break when this repo was copied
  # and used as a template.
  {{- $defaultRedisServiceHost := printf "%s-redis.%s" .Chart.Name .Release.Namespace  }}
  REDIS_SERVICE_HOST: {{ .Values.redis.host | default $defaultRedisServiceHost | quote }}
  REDIS_SERVICE_PORT: {{ .Values.redis.port | quote }}

  ELASTICSEARCH_CREATE: {{ .Values.elasticsearch.create | quote }}
  ELASTICSEARCH_POPULATE: {{ .Values.elasticsearch.populate | quote }}
  ELASTICSEARCH_HOST: {{ .Chart.Name }}-elasticsearch
  ELASTICSEARCH_PORT: {{ .Values.elasticsearch.port | quote }}
# datadog environment variables
  APM_ENABLED: {{ .Values.apm.enable | quote }}
  DATADOG_SERVICE_NAME: {{ .Chart.Name | quote }}
  DATADOG_ENV: {{ .Values.apm.datadog_env | quote }}
  DATADOG_TRACE_AGENT_HOSTNAME: {{ .Values.apm.datadog_trace_agent_hostname | quote }}
